config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :itineraries, only: %i[show update] do
    resources :students, only: %i[new create index]
  end
  resources :students, only: %i[edit update destroy show] do
    member do
      patch :move
    end
  end
  patch 'itineraries/:id/update_coordinates', to: 'itineraries#update_coordinates'
  get 'itineraries/:id/fetch_coordinates', to: 'itineraries#fetch_coordinates'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  has_many :students
  extend FriendlyId
  friendly_id :itinerary_title, use: :slugged

  private

  def itinerary_title
    SecureRandom.hex
  end

end

app/models/student.rb
class Student < ApplicationRecord
  acts_as_list

  belongs_to :itinerary

  validates :child_name, :child_address, :position, :parents_name, :parents_email, presence: true
  validates :parents_email, format: { with: /\S+@\S+\.\S+/ }

  geocoded_by :child_address, :latitude => :latitude_child, :longitude => :longitude_child
  after_validation :geocode, if: :will_save_change_to_child_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :itinerary
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :home_address, :school_address, :car_model, :car_plate, :car_color, presence: true
  validates :car_plate, format: { with: /[a-zA-Z]{3}[0-9][0-9a-zA-Z][0-9]{2}/, message: 'Apenas letras e números' }

  geocoded_by :home_address, :latitude  => :latitude_home, :longitude => :longitude_home
  geocoded_by :school_address, :latitude  => :latitude_school, :longitude => :longitude_school
  after_validation :geocode, if: :will_save_change_to_home_address?
  after_validation :geocode, if: :will_save_change_to_school_address?

  after_create :create_itinerary

  private

  def create_itinerary
    Itinerary.create(user: self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :home_address, :school_address, :car_model, :car_plate, :car_color])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :home_address, :school_address, :car_model, :car_plate, :car_color])
  end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :fetch_coordinates]

  def show
    @itinerary = Itinerary.friendly.find(params[:id])
    redirect_to root_path unless params[:id] == @itinerary.slug

    @markers = @itinerary.students.order(:position).map do |student|
      { lat: student.latitude_child, lng: student.longitude_child }
    end

    @points = {
      origin: {
        lat: @itinerary.user.latitude_home,
        lng: @itinerary.user.longitude_home
      },

      waypoints: @itinerary.students.order(:position).map do |student|
        {
          position: student.position,
          lat: student.latitude_child,
          lng: student.longitude_child
        }
      end,

      destination: {
        lat: @itinerary.user.latitude_school,
        lng: @itinerary.user.longitude_school
      }
    }
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    @student = Student.find(params[:id])
    @itinerary.current_sequence = @student.position
    @itinerary.update
    redirect_to itinerary_path(@itinerary)
  end

  def update_coordinates
    @itinerary = Itinerary.find(params[:id])
    @itinerary.latitude = params[:latitude]
    @itinerary.longitude = params[:longitude]
    @itinerary.save!
  end

  def fetch_coordinates
    @itinerary = Itinerary.find(params[:id])
    @coordinates = { latitude: @itinerary.latitude, longitude: @itinerary.longitude }.to_json
    render json: @coordinates
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @itinerary = current_user.itinerary
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[edit show update destroy move]
  before_action :set_itinerary, only: %i[index create new destroy]

  def index
    @students = Student.where(itinerary: @itinerary).order(:position)
  end

  def show
  end

  def new
    @student = Student.new
    @student.itinerary = @itinerary
  end

  def create
    @student = Student.new(student_params)
    @student.itinerary = @itinerary

    if @student.save
      mail = StudentMailer.with(student: @student).create_confirmation
      mail.deliver_now
      redirect_to itinerary_students_path(@student.itinerary_id)

    else
      render :new
    end
  end

  def edit
  end

  def update
    @student.update(student_params)
    redirect_to itinerary_students_path(@student.itinerary_id)
  end

  def destroy
    @student.destroy
    redirect_to itinerary_students_path(@student.itinerary_id)
  end

  def move
    @student.insert_at(params[:position].to_i)
    head :ok
  end

  private

  def student_params
    params.require(:student).permit(:child_name, :child_address, :position, :parents_name, :parents_email)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def set_itinerary
    @itinerary = Itinerary.friendly.find(params[:itinerary_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/itineraries/show.html.erb
<div class="map"
  data-controller="mapbox trip"
  data-mapbox-points-value="<%= @points.to_json %>"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-mapbox-id-value="<%= @itinerary.id %>"
  data-trip-id-value="<%= @itinerary.id %>">
  <% if current_user == @itinerary.user %>
    <button data-trip-target="button" data-action="click->trip#startRouteHideButton" class="demo__button d-flex align-items-center justify-content-center"><i class="fas fa-location-arrow" style="color: #000; margin-right: .9rem; font-size: 1.5rem"></i>Iniciar</button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cade o Tio?</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'cade_o_tio_browser_1.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="intro-home">
  <%= image_tag "cade_o_tio_circulo_preto.png",  class: "logo-home" %>
</div>

<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4 col-sm-offset-4">
      <div class="home-itens">
        <div class="secundary__buttons">
          <%= link_to new_itinerary_student_path(@itinerary, @student), class: "secondary__button" do %>
            <i class="fas fa-user-plus" style="font-size: 2.5rem; margin-left: .7rem"></i>
            <p class="m-0" style="font-size: 1.2rem">Criança</p>
          <% end %>
          <%= link_to itinerary_students_path(@itinerary), class: "tertiary__button" do %>
            <i class="fas fa-edit" style="font-size: 2.5rem; margin-bottom: .5rem; margin-left: .5rem"></i>
            <p style="margin: 0; font-size: 1.2rem">Editar itinerário</p>
          <% end %>
        </div>
        <%= link_to itinerary_path(@itinerary), class: "primary__button" do %>
          <i class="fas fa-map-marked-alt" style="font-size: 50px; margin: 10px 5px 25px 9px"></i>
          <p class="m-0">Visualizar itinerário</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_completo.png" %>
    <% end %>

    <div class="d-flex">
      <% if user_signed_in? %>
        <span class="d-flex align-items-center">
          <h4 id="greeting">Olá, <%= current_user.first_name %>!</h3>
        </span>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="d-flex align-items-center">
          <%= image_tag "onibus_avatarpng.png", class: "avatar" %>
        </span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <hr class="separator">
          <li class="nav-item">
            <%= link_to new_itinerary_student_path(current_user.itinerary), class: "nav-link" do %>
              <p><i class="fas fa-user-plus"></i> Cadastrar criança</p>
            <% end %>
          </li>
          <hr class="separator">
          <li class="nav-item">
            <%= link_to itinerary_students_path(current_user.itinerary), class: "nav-link" do %>
              <p><i class="fas fa-edit"></i> Editar itinerário</p>
            <% end %>
          </li>
          <hr class="separator">
          <li class="nav-item">
            <%= link_to itinerary_path(current_user.itinerary), class: "nav-link" do %>
              <p><i class="fas fa-eye"></i> Visualizar itinerário</p>
            <% end %>
          </li>
          <hr class="separator">
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <p><i class="fas fa-sign-out-alt"></i> Log out</p>
            <% end %>
          </li>
          <hr class="separator">
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <p><i class="fas fa-sign-in-alt"></i> Login</p>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/students/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4 col-sm-offset-4">
      <div class="intro">
        <h1 class="title-form">Cade o tio?</h1>
        <%= image_tag "cade_o_tio_circulo_preto.png",  class: "logo-form" %>
      </div>


      <div class="form-child">
        <%= simple_form_for student do |f| %>
        <%= f.input :child_name, label: 'Nome da criança' %>
        <%= f.input :child_address, label: 'Endereço da criança', input_html: { data: { geocoder_target: "address" }, class:"d-none" },
                    wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
        <%= f.input :position, label: 'Sequência' %>
        <%= f.input :parents_name, label: 'Nome do(a) responsável' %>
        <%= f.input :parents_email, label: 'E-mail do(a) responsável' %>
        <%= f.button :submit, value: 'Enviar', class: 'submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form', student: @student %>

app/views/students/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12">
      <div>
        <h1 id="title-students" class="text-center my-5">Crianças</h1>
      </div>
      <div  class="cards-student-index"
            data-controller='sequence studentinfo'
            data-sequence-url="/students/:id/move">
        <% @students.each do |student| %>
          <div data-id="<%= student.id %>" >
            <div>
              <%= link_to student_path(student),  class: 'student-index-link mb-3' do %>
                <div class="card-product-student-index mb-3"
                data-action="click->studentinfo#revealContent"
                data-id="<%= student.id %>">
                  <div class="card-product-infos-student d-flex">
                    <%= image_tag "icon-student.svg" %>
                    <div class="card-product-infos-student-index">
                      <h2><%= student.child_name %></h2>
                      <p><%= student.child_address %></p>
                    </div>
                  </div>
                  <div class="students-info">
                    <ul class="d-none mt-1" data-studentinfo-target="content"
                                      data-id="<%= student.id %>">
                      <hr>
                      <li><p><i class="fas fa-child"></i> Nome: <%= student.child_name %></p></li>
                      <hr>
                      <li><p><i class="fas fa-map-marker-alt"></i> Endereço: <%= student.child_address %></p></li>
                      <hr>
                      <li><p><i class="fas fa-user"></i> Responsável: <%= student.parents_name %></p></li>
                      <hr>
                      <li><p><i class="fas fa-paper-plane"></i> Email: <%= student.parents_email %></p></li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
            <div>
              <%= link_to edit_student_path(student), class: 'btn-student-edit d-none test',
                                                      data: { studentinfo_target: "icon",
                                                      id: student.id } do %>
                <p class="btn btn-edit-student  w-100" data-action="click->edit-student#displayForm">
                  Edite
                </p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center">
        <%= link_to 'Gerar itinerário', itinerary_path(@itinerary), class: 'btn-generate-iti my-3 w-100 p-3', style: "font-weight: bold; font-size: 1.1rem" %>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4 col-sm-offset-4">
      <div class="intro">
        <h1 class="title-form">Cadastro de criança</h1>
        <%# <%= image_tag "cade_o_tio_circulo_preto.png",  class: "logo-form" %>
      </div>

      <div class="form-child">
        <%= simple_form_for [@itinerary, @student] do |f| %>
        <%= f.input :child_name, label: 'Nome da criança' %>
        <%= f.input :child_address, label: 'Endereço da criança', input_html: { data: { geocoder_target: "address" }, class:"d-none" },
                    wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
        <%= f.input :position, label: 'Sequência' %>
        <%= f.input :parents_name, label: 'Nome do(a) responsável' %>
        <%= f.input :parents_email, label: 'E-mail do(a) responsável' %>
        <%= f.button :submit, value: 'Cadastrar', class: 'submit-button', data: { disable_with: 'Cadastrando...' } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="container pb-5">
  <div class="row justify-content-center">
    <div class="col-xs-12">
      <%= image_tag "icon-student.svg" %>
      <div class="mt-3">
        <ul>
          <li><p class="info__student">Nome: <%= @student.child_name %></p></li>
          <li><p class="info__student">Endereço: <%= @student.child_address %></p></li>
          <li><p class="info__student">Responsável: <%= @student.parents_name %></p></li>
          <li><p class="info__student">Email: <%= @student.parents_email %></p></li>
      <%= link_to 'Back', :back, class: 'btn btn-primary mt-2' %>
      <%= link_to 'Edit', '#', class: 'btn btn-warning mt-2' %>
        </ul>
      </div>
    </div>
  </div>
</div>